### ISSUE TITLE
プログラムの実行について

### ISSUE THREAD

**Issue by fujihalab** [takeru0001/research#27]
takeru0001さん，

千葉工大の藤原です．ご無沙汰していますが，お元気ですか？

卒研のプログラムを今年の４年生に勉強してもらっています．
本日，本プロジェクトのプログラムを実行してみましたが，
simulator.pyの491行目でエラーが出るようです．

---
$ python3 simulator.py
number_of_cars: 2
num_of_division: 9
epsilon greedy: 0.1
(37.789895827461, -122.4196618795395, 37.792380016410476, -122.41523623466492)
got map
### create cars ended ### 2021-11-18 13:09:48.967529
92.49999999906868 505.0 260.99999999813735 554.0
### Start of simulation ### 2021-11-18 13:09:49.070352
(4, 1)
Traceback (most recent call last):
  File "simulator.py", line 654, in <module>
    ani.save(str(epsilon) + "sfc-small.mp4", writer="ffmpeg")
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 1173, in save
    anim._draw_next_frame(d, blit=False)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 1208, in _draw_next_frame
    self._draw_frame(framedata)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 1776, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "simulator.py", line 491, in animate
    if ((index_x, index_y) in i.keys()):
AttributeError: 'tuple' object has no attribute 'keys'

---

本件について，エラーの原因が何か分かれば，教えてもらえたら幸いです．

お手数ですが，どうぞよろしくお願いします．

藤原明広

**Comment by takeru0001** [comment]
藤原先生
ご無沙汰しております。

調べましたところ、最後の変更がコミットされていませんでした。
[refactor](https://github.com/takeru0001/research/tree/refactor)ブランチにプッシュしましたので、ご確認いただけますでしょうか。

自分でもdockerで環境構築し試したのですが、メモリが足りず強制終了されてしましました... 
```
root@00425d5f21a7:~/opt/g-research# python3 simulator.py
5number_of_cars: 5
num_of_division: 5
epsilon greedy: 0.4
(37.606616172899535, -122.51678466796874, 37.81086891407298, -122.35267639160156)
Lowered zoom level to keep map size reasonable. (z = 12)
got map
998
0.001002004008016032
### create road network started ### 2021-11-18 21:15:18.397902
強制終了
root@00425d5f21a7:~/opt/g-research# ls
```

お忙しいところ恐縮ですが、よろしくお願いいたします。

中山

**Comment by fujihalab** [comment]
返信をありがとうございます．reactorブランチのプログラムを確認してみましたが，
以下のように同じエラーが出ました．

---
$ python3 simulator.py 
number_of_cars: 2
num_of_division: 9
epsilon greedy: 0.1
(37.789895827461, -122.4196618795395, 37.792380016410476, -122.41523623466492)
got map
### create road network started ### 2021-11-20 03:03:33.968190
### create road network ended ### 2021-11-20 03:03:33.989390
### create road segments started ### 2021-11-20 03:03:33.989439
### create road segments ended ### 2021-11-20 03:03:33.989570
### create cars started ### 2021-11-20 03:03:33.989577
### create cars ended ### 2021-11-20 03:03:33.990194
92.49999999906868 505.0 260.99999999813735 554.0
### map image loading ### 2021-11-20 03:03:34.001039
### map image loaded ### 2021-11-20 03:03:34.026194
### Start of simulation ### 2021-11-20 03:03:34.063245
Traceback (most recent call last):
  File "simulator.py", line 653, in <module>
    ani.save(str(epsilon) + "sfc-small.mp4", writer="ffmpeg")
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1152, in save
    anim._draw_next_frame(d, blit=False)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1192, in _draw_next_frame
    self._draw_frame(framedata)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1755, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "simulator.py", line 490, in animate
    if ((index_x, index_y) in i.keys()):
AttributeError: 'tuple' object has no attribute 'keys'
---

大きなマップを使うとメモリが足りなくなって，エラーの場所より手前で終了します
ので，以下のsfc_small.geojsonとsfc_small.net.xmlに切り替えて，もう一度実行して
もらえたらと思います．

[sfc_small.zip](https://github.com/takeru0001/research/files/7572149/sfc_small.zip)

可能であればバグを確認して，修正方法についてコメントをもらえたら幸いです．
お手数ですが，どうぞよろしくお願いします．

藤原

**Comment by takeru0001** [comment]
`geojson`ファイル`xml`ファイルのご共有ありがとうございます。
自分がrefactorブランチで確認したところ、うまく動作しました。
本件とはあまり関係がないアニメーションをmp4ファイルに保存する箇所でエラーが発生したので、そちらは修正しました。pythonのバージョンによって起きる問題かと思っています。ちなみに自分がdockerで試したversionは3.6です。
念のため、使用したDockerFileを添付いたします。(stepが多いとgifで保存するのは辛いと思いますので、今回のは仮の修正で、後に本格的に修正する or 以前使用してたpythonのversionを探す必要がありそうです。)
[Dockerfile.zip](https://github.com/takeru0001/research/files/7582873/Dockerfile.zip)

修正内容
https://github.com/takeru0001/research/commit/1aeb51f2567b6455d2b6905d3afa37be7ae10100

以下がログです。
```
root@8522fb69e732:~/opt/g-research# python3 simulator.py
number_of_cars: 2
num_of_division: 2
epsilon greedy: 0.5
(37.789895827461, -122.4196618795395, 37.792380016410476, -122.41523623466492)
got map
25
0.04
### create road network started ### 2021-11-22 09:19:13.379800
### create road network ended ### 2021-11-22 09:19:13.464798
### create road segments started ### 2021-11-22 09:19:13.464952
### create road segments ended ### 2021-11-22 09:19:13.465278
### create cars started ### 2021-11-22 09:19:13.465291
### create cars ended ### 2021-11-22 09:19:13.468848
92.49999999906868 505.0 260.99999999813735 554.0
### map image loading ### 2021-11-22 09:19:13.550788
### map image loaded ### 2021-11-22 09:19:13.751774
### Start of simulation ### 2021-11-22 09:19:13.837298
animation step: 100 2021-11-22 09:19:39.626258
animation step: 200 2021-11-22 09:20:05.994217
animation step: 300 2021-11-22 09:20:31.502092
animation step: 400 2021-11-22 09:20:57.593024
animation step: 500 2021-11-22 09:21:23.466329
[{(1, 0): {'reward': -0.08051056338299231, 'count': 9, 'step': 344, 'reward per step': -0.00023404233541567533}, (1, 1): {'reward': -0.0006501849054082503, 'count': 1, 'step': 13, 'reward per step': -5.0014223492942326e-05}, (0, 0): {'reward': 3.5539364997075746, 'count': 3, 'step': 119, 'reward per step': 0.029865012602584663}, (0, 1): {'reward': -0.02084766215242978, 'count': 1, 'step': 0, 'reward per step': 0}}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}]
root@8522fb69e732:~/opt/g-research# ls -t
```

次に先生からいただいたzipファイルの`simulator.py`を確認したところ、最新の`refactor`ブランチと差分がいくつかありましたので、そちらをなくしていただければと思います。（下記の画像箇所など(左:先生からいただいたファイル 右:最新`refactor`ブランチ)）
![スクリーンショット 2021-11-23 1 22 15](https://user-images.githubusercontent.com/58085267/142898614-60e27870-542a-48b5-a723-d8abd3fb6387.png)

念のため、主に使用する`simulator.py`と`ride_prob.py`を圧縮してお送りしておきます。
[simulator.zip](https://github.com/takeru0001/research/files/7582784/simulator.zip)

少し複雑になってしまっている箇所を追記しておきます。
買っていただいたデータ(`cabspottingdata`)から`analyze_mobility.py`や`analyze_returner.py`でreturnerのcarデータを抽出しているのですが、その際にできるデータの一覧のファイル`_cabs.txt`が元データと抽出したデータでは表記方法が異なってしまったため、`ride_prob.py`の添付場所で使用する関数を手動で変更する必要があります。
https://github.com/takeru0001/research/blob/1aeb51f2567b6455d2b6905d3afa37be7ae10100/ride_prob.py#L182
元の買ったデータのままシミュレーションする場合(`cabspottingdata`)→`get_filepath_of_selected_taxies()`を使用
上記のように抽出したデータを使用する場合→`get_filepath_of_taxies()`を使用

上記の箇所を変更する必要があり、すこし面倒ですがご確認よろしくお願いいたします。
